//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Identity_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Identity_Users_roles
    {
        public int userId { get; set; }
        public string userName { get; set; }
        public string userEmail { get; set; }
        public bool userStatus { get; set; }
        public string userRed { get; set; }
        public int IdRol { get; set; }
    
        public virtual role_identity_nv role_identity_nv { get; set; }
    }
}
